"""Frozen fixtures generated by the original project before extraction."""
import hashlib
import json
import numpy as np

from strategic_agents.agents.ippo_controller import pricing_features
from strategic_agents.envs.pricing import AgentAction, PricingMarketEnv
from strategic_agents.evaluation.regret import counterfactual_reward, price_grid


def test_pricing_reward_fixture_matches_original():
    expected = {
        "agent_0": 107.01766242303704, "agent_1": 78.68285334011709,
        "agent_2": 54.95616957340343, "agent_3": 37.93184192273085,
        "agent_4": 26.01267315662401,
    }
    env = PricingMarketEnv(seed=19, num_rounds=3); env.reset(19)
    prices = {f"agent_{i}": 7.5 + i*.5 for i in range(5)}
    result = env.step({a: AgentAction(a, "set_price", {"price": p}) for a, p in prices.items()})
    assert result.rewards == expected


def test_regret_candidate_fixture_matches_original():
    values = [counterfactual_reward(9.5, .2, p) for p in price_grid()]
    digest = hashlib.sha256(json.dumps(values, separators=(",", ":")).encode()).hexdigest()
    assert digest == "0107be09498c42b5114a32a4c2809f7548ddfcda8befcbfefefcfb87855b2c84"


def test_state_intent_feature_fixture_matches_original():
    env = PricingMarketEnv(seed=19, num_rounds=3); env.reset(19)
    prices = {f"agent_{i}": 7.5 + i*.5 for i in range(5)}
    observation = env.step({a: AgentAction(a, "set_price", {"price": p}) for a, p in prices.items()}).observations["agent_0"]
    expected_base = np.asarray([.3333333432674408, .1666666716337204, 0., .07134510576725006,
        .9920378923416138, .20000000298023224, .25, .30000001192092896,
        .03293059021234512, .05245523527264595, 1.], dtype=np.float32)
    intents = ("undercut_competitors", "hold_price", "raise_margin", "clear_inventory", "avoid_price_war")
    for index, intent in enumerate(intents):
        expected = np.concatenate([expected_base, np.eye(5, dtype=np.float32)[index]])
        assert np.array_equal(pricing_features(observation, intent), expected)
